steps:
  - label: "boostsecurity scanner"
    plugins:
      - boostsecurityio/boostsec-scanner#v4:
          registry_module: boostsecurityio/brakeman
#       - boostsecurityio/boostsec-scanner#v4:
#           registry_module: boostsecurityio/semgrep
#         env:
#           SEMGREP_RULES: .semgrep/
      - boostsecurityio/boostsec-scanner#v4:
          registry_module: boostsecurityio/bundler-audit
