env:
#   SEMGREP_RULES: "p/ruby"
#   SEMGREP_RULES: "p/ruby .semgrep/"
  SEMGREP_RULES: "p/ruby https://raw.githubusercontent.com/boost-sandbox/railsgoat/master/.semgrep/rules.yaml"
steps:
  - label: "boostsecurity scanner"
    plugins:
      - boostsecurityio/boostsec-scanner#v4:
          registry_module: boostsecurityio/brakeman
      - boostsecurityio/boostsec-scanner#v4:
          registry_module: boostsecurityio/semgrep
      - boostsecurityio/boostsec-scanner#v4:
          registry_module: boostsecurityio/bundler-audit
