name: boostsecurity.io
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
jobs:
  boost-sast-dev:
    name: SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Brakeman
#         uses: boostsecurityio/boostsec-scanner-github@v4
#         env:
#           BOOST_SCANNER_REGISTRY_REPO: https://github.com/boostsecurityio/scanner-testing.git#brakeman/update-image-to-fix-ruleid
        with:
          api_token: ${{ secrets.BOOST_API_KEY }}
          registry_module: boostsecurityio/brakeman
          log_level: DEBUG
